FAILED TEST LOG
  ✘ You should view all the data in "characters" ordered by "name"

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(selectAll.test(lastLog) && !/ERROR/.test(lastLog))

at Context.<anonymous> (test/790.test.js:9:5)
FAILED TEST LOG
  ✘ You should view all the data in "characters" ordered by "name"

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(selectAll.test(lastLog) && !/ERROR/.test(lastLog))

at Context.<anonymous> (test/790.test.js:9:5)
FAILED TEST LOG
  ✘ "characters" should have the "name" column as its primary key

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(false)

at Context.<anonymous> (test/800.test.js:24:7)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
FAILED TEST LOG
  ✘ You should display the details of the "characters" table

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(/Table"public\.characters"/.test(lastQueryResult))

at Context.<anonymous> (test/880.test.js:8:5)
FAILED TEST LOG
  ✘ You should display the details of the "characters" table

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(/Table"public\.characters"/.test(lastQueryResult))

at Context.<anonymous> (test/880.test.js:8:5)
FAILED TEST LOG
  ✘ You should display the details of the "characters" table

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(/Table"public\.characters"/.test(lastQueryResult))

at Context.<anonymous> (test/880.test.js:8:5)
FAILED TEST LOG
  ✘ "mario_database" should have a table named "actions" that has an "action_id" column with the correct properties

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(false)

at Context.<anonymous> (test/1380.test.js:22:7)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
FAILED TEST LOG
  ✘ "mario_database" should have a table named "actions" that has an "action_id" column with the correct properties

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(false)

at Context.<anonymous> (test/1380.test.js:22:7)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
FAILED TEST LOG
  ✘ The "character_actions" table should have three rows for Yoshi's actions

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(false)

at Context.<anonymous> (test/1540.test.js:20:7)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
FAILED TEST LOG
  ✘ The "character_actions" table should have three rows for Yoshi's actions

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(false)

at Context.<anonymous> (test/1540.test.js:20:7)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
FAILED TEST LOG
  ✘ You should display the tables with suggested command

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(d.test(lastLog))

at Context.<anonymous> (test/1630.test.js:9:5)
FAILED TEST LOG
  ✘ You should display the tables with suggested command

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(d.test(lastLog))

at Context.<anonymous> (test/1630.test.js:9:5)
FAILED TEST LOG
  ✘ You should view all the data from "characters" and "more_info" with a JOIN statement

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(correctNumberOfRows && test1 && column_1 && column_2)

at Context.<anonymous> (test/1660.test.js:13:5)
